messages:
  noPermission: "&cУ вас нет прав на использование данной команды!"
  noArgs: "&cНедостаточно аргументов!"
  balance: "&fВаш баланс: &6{money} мон."
  salary: "&fВы получили зарплату в виде &6{money} мон.! &7(бонус x{bonus})"
  edited: "&fВы успешно изменили монетки игрока &6{player}!"
  reload: "&aВы успешно перезагрузили плагин!"
config:
  salaryTime: 300 # раз в сколько секунд выдаются монетки?
  salary: 200